---
title: "Data vizualization practice"
author: "Haylee Oyler"
format: html
editor: source
execute:
  warning: false
  message: false
editor_options: 
  chunk_output_type: console
---

#### Setup
```{r}
rm(list = ls())
library(tidyverse)
library(here)
library(janitor)
library(skimr)
library(extrafont)
# library(ggimage)
# Specifically for plots:
library(patchwork)
library(ggrepel)
library(gghighlight)
library(paletteer)
library(ggExtra)
library(ggbeeswarm)
library(ggstream)
library(RColorBrewer)
library(plotfun)
```

## Do your data viz worst

```{r}
# Read in data ----
space_launches <- read_csv(here("data", "space_launches.csv"))
```

```{r}
#| eval: false
# Check it out ----
skim(space_launches)
dim(space_launches)
summary(space_launches)

length(unique(space_launches$state_code))
```

```{r}
# data wrangling ----
year_state <- space_launches %>% 
  group_by(state_code) %>% 
  summarise(n = n())

comb_ys <- left_join(year_state, space_launches, join_by(state_code))

comb_ys <- comb_ys %>% 
  select(state_code, n, launch_year) %>% 
  filter(state_code != "NA")
```

```{r}
# Worst possible viz ----
ggplot(comb_ys, aes(x = launch_year, y = state_code)) + 
  geom_tile(aes(fill = n)) +
  scale_fill_gradientn(colors = c("slateblue4", "orangered", "olivedrab", "khaki")) +
  theme(panel.background = element_rect(color = "purple", size = 12, fill = "yellow3"),
        panel.grid.major = element_line(color = "red"),
        axis.text.x = element_text(color = "blue", size = 13, family= "Ink Free"),
        axis.text.y = element_text(color = "deeppink", size = 13, family= "Ink Free"),
        axis.title.x = element_text(color = "yellowgreen", size = 15, family= "Segoe Print"),
        axis.title.y = element_text(color = "gray70", size = 15, family= "Segoe Print"),
        title = element_text(color = "aquamarine4", size = 18, family = "Impact"), 
        plot.background = element_rect(fill = "aquamarine")) +
  annotate("text", x = 1970, y = "KR", label = "SPACE!", color = "purple") + 
  annotate("text", x = 2005, y = "I-ELDO", label = "WOWZA", color = "white") +
  labs(x = "year", 
       y = "state", 
       title = "yahoo")

```

## Data wrangling

```{r}
# Read in the data ----
sf_ghg <- read_csv(here("data", "San_Francisco_Communitywide_Greenhouse_Gas_Inventory.csv")) %>% clean_names()
```

```{r}
ex_a <- sf_ghg %>% 
  group_by(sector_general, calendar_year) %>% 
  summarise(total_emissions = sum(emissions_mt_co2e))

ex_b <- sf_ghg %>% 
  group_by(commodity_type, calendar_year) %>% 
  summarise(total_emissions = sum(emissions_mt_co2e))

ex_c <- sf_ghg %>% 
  filter(calendar_year >= 2005, sector_detail2 %in% str_subset(sf_ghg$sector_detail2, "PG&E")) %>%
  select(calendar_year, sector_detail2, emissions_mt_co2e)
```

## Do you data viz best

```{r}
# Wrangling ----
#WAIT lets make a viz where you can see both the sector and the fuel type and how they're changing over time. 

summary(sf_ghg)
length(unique(sf_ghg$sector_gpc_detail))

pretty_plot <- sf_ghg %>% 
  select(calendar_year, emissions_mt_co2e, sector_general, sector_detail1, commodity_type) %>% 
  group_by(sector_general, calendar_year) %>% 
  summarise(total_emissions = sum(emissions_mt_co2e))
```

```{r}
ggplot(pretty_plot, aes(x = calendar_year, y = total_emissions)) + 
  # geom_point(aes(color = commodity_type)) +
  geom_line(aes(color = sector_general)) +
  theme_minimal() +
# scale_color_manual(values = brewer.pal(n = 6, name = "PRGn")) +
  theme(panel.background = element_rect(fill = "gray90"), 
        plot.background = element_rect(fill = "gray90"), 
        panel.grid.major = element_line(color = "ghostwhite"), 
        axis.title = element_text(color = "green3"), 
        axis.text = element_text(color = "green4"), 
        text = element_text(family = "Verdana")) +
  labs(title = "Total CO2 Emissions by Sector from 1990 to 2020", 
       x = "Year", 
       y = "CO2 Emissions (Mt CO2e)")

# length(unique(sf_ghg$calendar_year)) = 10
# length(unique(sf_ghg$sector_detail1)) = 14
# length(unique(sf_ghg$sector_detail2)) = 46
# length(unique(sf_ghg$commodity_type)) = 20
```


```{r}
#Best possible viz ----
ggplot(pretty_plot, aes(x = calendar_year, y = total_emissions)) + 
  geom_area(aes(fill = sector_general), stat = "identity", position = "stack", alpha = 0.5, na.rm = TRUE) +
  scale_fill_aoba(palette = "aqua")+
  geom_line(aes(color = sector_general), na.rm = TRUE, show.legend = FALSE) +
  scale_color_aoba(palette = "aqua", discrete = TRUE) +
  labs(title = "Total CO2 Emissions by Sector from 1990 to 2020", 
       x = "Year", 
       y = "CO2 Emissions (Mt CO2e)") +
  guides(fill = guide_legend(title = "Sector")) +
  theme(
    # add border 1)
    panel.border = element_rect(colour = aoba_color("aqua2"), fill = NA, linetype = 1, size = 0.1),
    # color background 2)
    panel.background = element_rect(fill = "white"),
    # change entire background
    plot.background = element_rect(fill = "white"), 
    # modify grid 3)
    panel.grid.major.x = element_line(colour = aoba_color("aqua2"), linetype = 1, linewidth = 0.2),
    panel.grid.minor.x = element_blank(),
    panel.grid.major.y =  element_line(colour = aoba_color("aqua2"), linetype = 1, linewidth = 0.2),
    panel.grid.minor.y = element_blank(),
    # modify text, axis and colour 4) and 5)
    axis.text = element_text(colour = aoba_color("aqua2"), face = "italic", family = "Times New Roman"),
    axis.title = element_text(colour = aoba_color("aqua2"), family = "Times New Roman", size = 13),
    axis.ticks = element_line(colour = aoba_color("aqua2"), linewidth = 0.2),
    # legend at the bottom 6)
    legend.position = "bottom", 
    # title
    title = element_text(colour = aoba_color("aqua3"), family = "Times New Roman", size = 14, face = "bold")
  )
```

```{r}
ggplot(pretty_plot, aes(x = calendar_year, y = total_emissions)) + 
  geom_area(aes(fill = sector_general), stat = "identity", position = "stack", alpha = 0.5, na.rm = TRUE) +
  scale_fill_aoba(palette = "aqua")+
  geom_line(aes(color = sector_general), na.rm = TRUE, show.legend = FALSE) +
  scale_color_aoba(palette = "aqua", discrete = TRUE) +
  labs(title = "Total CO2 Emissions by Sector from 1990 to 2020", 
       x = "Year", 
       y = "CO2 Emissions (Mt CO2e)") +
  guides(fill = guide_legend(title = "Sector")) +
  theme_aoba()
```

